version: "3"
services:
  named:
    build: .
    image: autechgemz/named-src
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TRUSTED_NET: 'any'
    restart: always
    cap_add:
      - DAC_READ_SEARCH
      - SYS_RESOURCE
      - NET_ADMIN
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD","dig","@localhost","localhost","+norec"]
      interval: 5m
      timeout: 10s
      retries: 3
